case stmt restrurcture (back to indents)

diff --git a/bin/bin/functions/X11/functions/dmenu/reminder b/bin/bin/functions/X11/functions/dmenu/reminder
--- a/bin/bin/functions/X11/functions/dmenu/reminder
+++ b/bin/bin/functions/X11/functions/dmenu/reminder
@@ -13,15 +13,15 @@ EDIT='edit'
 while appmt=$(reminder 52 | sed  "1i$(X $ADD)\n$(X $EDIT)" | rmenu 'Appointment' -no-custom) || exit ;do
   unset error
   case "${appmt#$(X)}" in
-  "$ADD" ) while date=$(echo | rmenu "On date$error") || break ;do
-             [ -z "$date" ] && break
-             date --date "$date" >/dev/null 2>&1 || { error=": $date ?"; continue; }
-             reminder "$date"
-             break
-           done ;;
-
-  "$EDIT") v -f -c 'normal|G' $REMINDERS ;;
-  *      ) v -f -c "/${appmt#*$SEP }$" $REMINDERS ;;
+    "$ADD" ) while date=$(echo | rmenu "On date$error") || break ;do
+               [ -z "$date" ] && break
+               date --date "$date" >/dev/null 2>&1 || { error=": $date ?"; continue; }
+               reminder "$date"
+               break
+             done ;;
+  
+    "$EDIT") v -f -c 'normal|G' $REMINDERS ;;
+    *      ) v -f -c "/${appmt#*$SEP }$" $REMINDERS ;;
   esac
 done
 
